name: pointagepro
description: PointagePro

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5
  http: ^1.2.2
  intl: ^0.19.0
  geolocator: ^13.0.1
  mobile_scanner: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/pointagepro_logo.png
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/icon/pointagepro_logo.png