// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJEsk9a_N_dYNYPYGoUIFHsOaW2G1wO6E',
    appId: '1:651818546130:web:d151485e3767aa788f4e0b',
    messagingSenderId: '651818546130',
    projectId: 'pointagepro-izs',
    authDomain: 'pointagepro-izs.firebaseapp.com',
    storageBucket: 'pointagepro-izs.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp84P7GdoqK1mr-vowNWQvt3u3Mk-TIRY',
    appId: '1:651818546130:android:e06650f9ce2ed1798f4e0b',
    messagingSenderId: '651818546130',
    projectId: 'pointagepro-izs',
    storageBucket: 'pointagepro-izs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD64lNYENVYTqcDtA_Xbcs5DoDaEpXJxQk',
    appId: '1:651818546130:ios:b232f0e8c66a36358f4e0b',
    messagingSenderId: '651818546130',
    projectId: 'pointagepro-izs',
    storageBucket: 'pointagepro-izs.firebasestorage.app',
    iosBundleId: 'com.izs.pointagepro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD64lNYENVYTqcDtA_Xbcs5DoDaEpXJxQk',
    appId: '1:651818546130:ios:5e8b5cb032d1d4cb8f4e0b',
    messagingSenderId: '651818546130',
    projectId: 'pointagepro-izs',
    storageBucket: 'pointagepro-izs.firebasestorage.app',
    iosBundleId: 'com.example.pointagepro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJEsk9a_N_dYNYPYGoUIFHsOaW2G1wO6E',
    appId: '1:651818546130:web:603584c1e7a601d18f4e0b',
    messagingSenderId: '651818546130',
    projectId: 'pointagepro-izs',
    authDomain: 'pointagepro-izs.firebaseapp.com',
    storageBucket: 'pointagepro-izs.firebasestorage.app',
  );
}
